export const ABA_MODULES = [
  {
    name: "EŞLEME BECERİLERİ (EB)",
    achievements: [
      "EB.1.1. Nesne-Nesne Eşleme (Aynı nesne)",
      "EB.1.2. Nesne Resimleri Eşleme (Aynı nesne)",
      "EB.1.3. Eylem Resimleri Eşleme (Aynı eylem)",
      "EB.1.4. Şekil Kutusu Eşleme",
      "EB.2.1. Nesne-Nesne Eşleme (Farklı nesne)",
      "EB.2.2. Nesne Resimleri Eşleme (Farklı nesne)",
      "EB.2.3. Eylem Resimleri Eşleme (Farklı eylem)",
      "EB.2.4. Resim-Nesne Eşleme",
      "EB.2.5. Renk Eşleme",
      "EB.3.1. Şekil Eşleme",
      "EB.3.2. Rakam Eşleme",
      "EB.3.3. Harf Eşleme",
      "EB.3.4. Gölge Eşleme",
      "EB.3.5. Ses Eşleme",
      "EB.4.1. Kelime-Kelime Eşleme",
      "EB.4.2. Klavyede Harf Eşleme",
      "EB.4.3. Sözcük-Nesne Eşleme",
      "EB.4.4. Sözcük Resim Eşleme",
      "EB.4.5. Sözcük Nesne Resim",
      "EB.4.6. Resimleri Kategorilerine Göre Eşleme",
      "EB.4.7. Görsel Bir Örüntü Modeli Verild. Nesneleri Örüntüye Göre Eşl.",
      "EB.4.8. İlişkili Resimleri Eşleme",
      "EB.4.9. Öykü Resim Eşleme",
      "EB.4.10. Renge ve Şekle göre Gruplama/Ayırma"
    ]
  },
  {
    name: "İFADE EDİCİ DİL BECERİLERİ (İEDB)",
    achievements: [
      "İEDB 1.1. Çıkardığı Sesleri Şarkı/Oyun İçinde Kullanma",
      "İEDB 1.2. Uyaran Sunulduğunda Talep Etme",
      "İEDB 1.3. Temel İhtiyaçlarını İfade Etme",
      "İEDB 2.1. Etkileşim Başlatma",
      "İEDB 2.2. Nesneler Varken Kendiliğinden Talep Etme",
      "İEDB 2.3. Nesne Adlandırma",
      "İEDB 2.4. Resim Adlandırma",
      "İEDB 2.5. Kişisel Bilgi Soruları Cevaplama",
      "İEDB 3.1. Vücut Bölümlerini Adlandırma",
      "İEDB 3.2. Nesne/Etkinlik Ortamda Yokken Kendiliğinden Talep Etme",
      "İEDB 3.3. Yer/Konum Bildiren Sözcükler Kullanma",
      "İEDB 3.4. Renk Adlandırma",
      "İEDB 3.5. Eylem Adlandırma",
      "İEDB 3.6. Bir Objenin Parçalarını Adlandırma",
      "İEDB 3.7. Evet-Hayır Kullanma (Somut Bilgiler)",
      "İEDB 3.8. Sıfat Kullanma",
      "İEDB 3.9. Neden-Sonuç İlişkisi Kurmayı Gerektiren Sorulara Cevap Verme",
      "İEDB 3.10. Zamir Kullanma",
      "İEDB 3.11. Bilgi Aktarma",
      "İEDB 3.12. TOLKİDO Kullanarak Tercih Bildirme",
      "İEDB 3.13. Öykü Sıralama",
      "İEDB 4.1. Şekil Adlandırma",
      "İEDB 4.2. Duygu Adlandırma",
      "İEDB 4.3. Kişi Tarif Etme",
      "İEDB 4.4. Kavram Adlandırma",
      "İEDB 4.5. Evet-Hayır Kullanma (Soyut Bilgiler)",
      "İEDB 4.6. Genel Bilgi Soruları Cevaplama",
      "İEDB 4.7. 5N1K Sorularını Cevaplama",
      "İEDB 4.8. İşlevini Söyleme",
      "İEDB 4.9. Kategorilerini Söyleme",
      "İEDB 4.10. İyelik Ekleri Kullanma",
      "İEDB 4.11. Eksik ve Yanlış Olanları Söyleme"
    ]
  },
  {
    name: "TAKLİT BECERİLERİ (TAK)",
    achievements: [
      "TAK 1.1. Nesneli Motor taklit",
      "TAK 1.2. Nesnesiz Motor Taklit",
      "TAK 2.1. Aynada Motor Hareketleri Taklit Etme",
      "TAK 2.2. Video Modeli ile Motor Taklit",
      "TAK 2.3. Ağız ve Dil Hareketlerinin Taklit Etme",
      "TAK 2.4. Motor ve Ses Taklidi Bir arada Yapma",
      "TAK 2.5. Şarkı/Oyun Etkinliğinde Hareket Taklit Etme",
      "TAK 3.1. Akran Motor Taklidi",
      "TAK 3.2. Grup Etkinliğinde Motor Taklit",
      "TAK 3.3. Hareketin Hızını Taklit Etme",
      "TAK 3.4. Hareketleri Yapılan Sıra ile Sırasını Taklit Etme",
      "TAK 4.1. Nesnelere Sırayla Dokunma Taklidi",
      "TAK 4.2. Gecikmiş Taklit",
      "TAK 4.3. Çok Basamaklı Taklit"
    ]
  },
  {
    name: "SÖZEL TAKLİT BECERİLERİ (ST)",
    achievements: [
      "ST 1.1. Ses Taklidi",
      "ST 1.2. Hece Taklidi",
      "ST 2.1. Sözcük Taklit Etme",
      "ST 2.2. Hayvan Sesleri ve Diğer Sesleri Taklit Etme",
      "ST 2.3. Cümle Taklidi",
      "ST 2.4. TOLKİDO ile Sözel Taklit",
      "ST 3.1. Konuşmanın farklı değişkenlerini taklit etme"
    ]
  },
  {
    name: "ALICI DİL BECERİLERİ (ADB)",
    achievements: [
      "ADB 1.1. Adına Tepki Verme",
      "ADB 1.2. Nesne Tanıma",
      "ADB 1.3. Resim Tanıma",
      "ADB 2.1. İnsan Tanıma",
      "ADB 2.2. Objelerle ile İlgili Yönergeleri Yerine Getirme",
      "ADB 2.3. Grup İçindeki İki Nesneyi Sırasıyla Ayırt Etme",
      "ADB 2.4. Büyük, Karmaşık Bir Resimdeki Nesneleri Ayırt Etme",
      "ADB 2.5. Temel Vücut Bölümlerini Ayırt Etme",
      "ADB 3.1. Bebek ve Resim Üzerinden Temel Vücut Böl. Gösterme",
      "ADB 3.2. Renk Tanıma",
      "ADB 3.3. Sesleri Ayırt Etme",
      "ADB 3.4. Eylemleri Ayırt Etme",
      "ADB 3.5. Yer/Konum Bildiren Sözcükleri Ayırt Etme",
      "ADB 4.1. Şekil Ayırt Etme",
      "ADB 4.2. Tüm Vücut Bölümlerini Tanıma",
      "ADB 4.3. Olumsuz İfadeleri Ayırt Etme",
      "ADB 4.4. Duyguları Ayırt Etme",
      "ADB 4.5. İşlevine Göre Ayırt Etme",
      "ADB 4.6. Özelliğine Göre Ayırt Etme",
      "ADB 4.7. Kategorilerine Göre Ayırt Etme",
      "ADB 4.8. Aynı ve Farklıyı Ayırt Etme",
      "ADB 4.9. Harf/Sözcük Ayırt Etme",
      "ADB 4.10. Canlı/Cansız Bir Varlığın Bütün Örneklerini Seçme",
      "ADB 4.11. İki Belirli Özelliği Verilen Nesne/Fotoğrafları Ayırt Etme",
      "ADB 4.12. Yanlış/Mantıksız Olanı Ayırt Etme",
      "ADB 4.13. Ara Renkleri Ayırt Etme"
    ]
  },
  {
    name: "ORTAK DİKKAT BECERİLERİ (OD)",
    achievements: [
      "OD 1.1. \"Bana Bak\" Yönergesine Tepkide Bulunma",
      "OD 1.2. Göz Kontağı Kurma",
      "OD 1.3. İletişim Ortağının Bakışlarını Takip Etme",
      "OD 1.4. \"…..'ya bak.\" Yönergesine Uygun Tepkide Bulunma",
      "OD 1.5. İşaret Parmağı ile İşaret Etme",
      "OD 1.6. Gösterilen İlginç Nesne/Durumlara Bakma",
      "OD 2.1. Başkalarının Dikkatini Bir Nesneye Yönlendirme",
      "OD 2.2. Yönerge Verildiğinde İlgisinin Olduğu Nesneyi Gösterme",
      "OD 2.3. İşaret Edilen Nesne/Kişiye Bakma",
      "OD 2.4. Başkalarının Sosyal Etkileşim Girişimine Bakarak ve/veya Konuşarak Tepki Verme",
      "OD 3.1. İlginç Nesne/Durumları İşaret Etme",
      "OD 3.2. Kendiliğinden İşaret/Bakışı Takip Ederek Hedeflenen Nesne/Duruma Bakma",
      "OD 3.3. Etkileşim Sırasında Göz Kontağını Sürdürme",
      "OD 3.4. İsimleri Söylenen/İşaret Edilen Nesne/Kişilere Bakma",
      "OD 4.1. İlginç Nesne/Durumlara İlişkin Duygu/Düşünce Paylaşmak Amacıyla Jest, Mimik veya Göz Teması Kullanma"
    ]
  },
  {
    name: "YÖNERGE TAKİP BECERİLERİ (YTB)",
    achievements: [
      "YTB 1.1. Tek Basamaklı Yönergeleri Takip Etme",
      "YTB 1.2. Bir Nesne ile İlgili Verilen Tek Bas. Yönergeleri Yerine Getirme",
      "YTB 2.1. İki Basamaklı yön. Takip Etme",
      "YTB 2.2. Bir Nesne ile İlgili Verilen Çok Bas. Yönergeleri Yerine Getirme",
      "YTB 2.3. Beklenmedik Bir Zamanda Verilen Yönergeyi Yerine Getirme",
      "YTB 2.4. Yönerge Verildiğinde Belirli Bir Alana Gitme",
      "YTB 3.1. Altı veya Daha Fazla Nesne Arasından Söyleneni Verme",
      "YTB 3.2. Altı veya Daha Fazla Resim Arasından Söyleneni Verme",
      "YTB 3.3. Verilen Yönergeleri İstenen Sıra ile Yerine Getirme",
      "YTB 3.4. Basit Grup Yönergelerini Takip Etme",
      "YTB 3.5. Basit Koşullu Yönergeleri Takip Etme",
      "YTB 3.6. Yönerge Takip Etme: Yazmaya Hazırlık",
      "YTB 4.1. Birbirinden Bağımsız Olarak Gerçklş. Üç Yön. Yerine Get.",
      "YTB 4.2. Mantık Kurarak Yönergeleri Yerine Getirme",
      "YTB 4.3. Belirli Birkaç Hareketi İlişkili Nesne ile Gösterme",
      "YTB 4.4. Söylenen Alana Gidip Verilen Yönergeyi Yerine Getirme",
      "YTB 4.5. Kağıt Kalem Kullanmayı Gerektiren yön. Takip Etme",
      "YTB 4.6. Karmaşık Grup Yönergelerini Takip Etme",
      "YTB 4.7. Karmaşık Koşullu Yönergeleri Takip Etme"
    ]
  }
];
